FROM deepestthought42/build-essentials:0.1
MAINTAINER Renee Klawitter <deepestthought42@gmail.com>

## install packages
RUN apt-get update && \
    apt-get install -y cmake libllvm3.7 "llvm-3.7-*" clang-3.7 "libclang-3.7-*"

ENV HOME /root



